dataset:
  type: text
  path: /inputs/data
  p_train: 0.8
  parameters:
    keep_linebreaks: True

tokenizer:
  type: EleutherAI/gpt-neo-125M
  parameters:
    pad_token: <|endoftext|>

model:
  type: EleutherAI/gpt-neo-125M

training_args:
  output_dir: /outputs/models
  overwrite_output_dir: True
  load_best_model_at_end: True
  num_train_epochs: 10
  per_device_train_batch_size: 6
  per_device_eval_batch_size: 6
  evaluation_strategy: epoch
  logging_strategy: epoch
  save_strategy: epoch
