jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/donaghhorgan/blindbot
      username: donaghhorgan
      password: secret:GITHUB_PASSWORD

  TrainModel:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cd /input/repo
        python -m pip install pipenv==2021.5.29
        pipenv install
        python -c "import torch; print(torch.__version__)"
      image: nvcr.io/nvidia/pytorch:21.02-py3
