name: Lint code base

on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: docker://github/super-linter:v3.14.5
        with:
          entrypoint: /action/lib/linter.sh  # Need to specify this to run actions locally (see nektos/act#298)
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
