name: Regression tests

on: push

jobs:
  regression:
    name: Regression tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --build-arg PIPENV_DEV=true -t $GITHUB_REPOSITORY:$GITHUB_SHA .

      - name: Run unit tests
        run: docker run --rm --entrypoint=python $GITHUB_REPOSITORY:$GITHUB_SHA -m pytest