name: Regression tests

on: push

jobs:
  regression:
    name: Regression tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: pipenv run pytest .
